spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: 123456
  flyway:
    enabled: true
    locations: classpath:db/migration

money:
  currency: руб.