spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: 123456
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
#    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: data.sql
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

money:
  currency: руб.
logging:
  level:
    root: error
    org.springframework.data: debug
